name: Deploy Docker Stack

on:
  push:
    paths:
      - 'index.html'
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client
      
      - name: Copy files to remote server
        run: |
          sftp -o StrictHostKeyChecking=no ip172-18-0-135-cpk33fq91nsg00eubg60@direct.labs.play-with-docker.com <<EOF
          put docker-compose.yml /root/
          put index.html /root/
          EOF

      - name: Execute Remote SSH Command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 8022
          script: |
            docker stack deploy -c docker-compose.yml fevertockens
